//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Cyotek.Data.Nbt
{
  partial class TagCollection
  {
    /// <summary>
    /// Creates and adds a new unnamed <see cref="TagByte"/> with the specified value.
    /// </summary>
    /// <param name="value">The value of the tag.</param>
    /// <returns>
    /// A <see cref="TagByte"/> containing the specified name and value.
    /// </returns>
    public TagByte Add(byte value)
    {
      TagByte tag;

      tag = TagFactory.CreateTag(value);

      this.Add(tag);

      return tag;
    }

    /// <summary>
    /// Creates and adds a new unnamed <see cref="TagShort"/> with the specified value.
    /// </summary>
    /// <param name="value">The value of the tag.</param>
    /// <returns>
    /// A <see cref="TagShort"/> containing the specified name and value.
    /// </returns>
    public TagShort Add(short value)
    {
      TagShort tag;

      tag = TagFactory.CreateTag(value);

      this.Add(tag);

      return tag;
    }

    /// <summary>
    /// Creates and adds a new unnamed <see cref="TagInt"/> with the specified value.
    /// </summary>
    /// <param name="value">The value of the tag.</param>
    /// <returns>
    /// A <see cref="TagInt"/> containing the specified name and value.
    /// </returns>
    public TagInt Add(int value)
    {
      TagInt tag;

      tag = TagFactory.CreateTag(value);

      this.Add(tag);

      return tag;
    }

    /// <summary>
    /// Creates and adds a new unnamed <see cref="TagLong"/> with the specified value.
    /// </summary>
    /// <param name="value">The value of the tag.</param>
    /// <returns>
    /// A <see cref="TagLong"/> containing the specified name and value.
    /// </returns>
    public TagLong Add(long value)
    {
      TagLong tag;

      tag = TagFactory.CreateTag(value);

      this.Add(tag);

      return tag;
    }

    /// <summary>
    /// Creates and adds a new unnamed <see cref="TagFloat"/> with the specified value.
    /// </summary>
    /// <param name="value">The value of the tag.</param>
    /// <returns>
    /// A <see cref="TagFloat"/> containing the specified name and value.
    /// </returns>
    public TagFloat Add(float value)
    {
      TagFloat tag;

      tag = TagFactory.CreateTag(value);

      this.Add(tag);

      return tag;
    }

    /// <summary>
    /// Creates and adds a new unnamed <see cref="TagDouble"/> with the specified value.
    /// </summary>
    /// <param name="value">The value of the tag.</param>
    /// <returns>
    /// A <see cref="TagDouble"/> containing the specified name and value.
    /// </returns>
    public TagDouble Add(double value)
    {
      TagDouble tag;

      tag = TagFactory.CreateTag(value);

      this.Add(tag);

      return tag;
    }

    /// <summary>
    /// Creates and adds a new unnamed <see cref="TagByteArray"/> with the specified value.
    /// </summary>
    /// <param name="value">The value of the tag.</param>
    /// <returns>
    /// A <see cref="TagByteArray"/> containing the specified name and value.
    /// </returns>
    public TagByteArray Add(byte[] value)
    {
      TagByteArray tag;

      tag = TagFactory.CreateTag(value);

      this.Add(tag);

      return tag;
    }

    /// <summary>
    /// Creates and adds a new unnamed <see cref="TagString"/> with the specified value.
    /// </summary>
    /// <param name="value">The value of the tag.</param>
    /// <returns>
    /// A <see cref="TagString"/> containing the specified name and value.
    /// </returns>
    public TagString Add(string value)
    {
      TagString tag;

      tag = TagFactory.CreateTag(value);

      this.Add(tag);

      return tag;
    }

    /// <summary>
    /// Creates and adds a new unnamed <see cref="TagList"/> with the specified value.
    /// </summary>
    /// <param name="value">The value of the tag.</param>
    /// <returns>
    /// A <see cref="TagList"/> containing the specified name and value.
    /// </returns>
    public TagList Add(TagCollection value)
    {
      TagList tag;

      tag = TagFactory.CreateTag(value);

      this.Add(tag);

      return tag;
    }

    /// <summary>
    /// Creates and adds a new unnamed <see cref="TagCompound"/> with the specified value.
    /// </summary>
    /// <param name="value">The value of the tag.</param>
    /// <returns>
    /// A <see cref="TagCompound"/> containing the specified name and value.
    /// </returns>
    public TagCompound Add(TagDictionary value)
    {
      TagCompound tag;

      tag = TagFactory.CreateTag(value);

      this.Add(tag);

      return tag;
    }

    /// <summary>
    /// Creates and adds a new unnamed <see cref="TagIntArray"/> with the specified value.
    /// </summary>
    /// <param name="value">The value of the tag.</param>
    /// <returns>
    /// A <see cref="TagIntArray"/> containing the specified name and value.
    /// </returns>
    public TagIntArray Add(int[] value)
    {
      TagIntArray tag;

      tag = TagFactory.CreateTag(value);

      this.Add(tag);

      return tag;
    }

    /// <summary>
    /// Creates and adds a new unnamed <see cref="TagLongArray"/> with the specified value.
    /// </summary>
    /// <param name="value">The value of the tag.</param>
    /// <returns>
    /// A <see cref="TagLongArray"/> containing the specified name and value.
    /// </returns>
    public TagLongArray Add(long[] value)
    {
      TagLongArray tag;

      tag = TagFactory.CreateTag(value);

      this.Add(tag);

      return tag;
    }

  }
}
