//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyotek.Data.Nbt.Serialization
{
  partial class TagReader
  {
    /// <summary>
    /// Reads a <see cref="T:byte" /> value.
    /// </summary>
    public abstract byte ReadByte();

    /// <summary>
    /// Reads a <see cref="T:short" /> value.
    /// </summary>
    public abstract short ReadShort();

    /// <summary>
    /// Reads a <see cref="T:int" /> value.
    /// </summary>
    public abstract int ReadInt();

    /// <summary>
    /// Reads a <see cref="T:long" /> value.
    /// </summary>
    public abstract long ReadLong();

    /// <summary>
    /// Reads a <see cref="T:float" /> value.
    /// </summary>
    public abstract float ReadFloat();

    /// <summary>
    /// Reads a <see cref="T:double" /> value.
    /// </summary>
    public abstract double ReadDouble();

    /// <summary>
    /// Reads a <see cref="T:byte[]" /> value.
    /// </summary>
    public abstract byte[] ReadByteArray();

    /// <summary>
    /// Reads a <see cref="T:string" /> value.
    /// </summary>
    public abstract string ReadString();

    /// <summary>
    /// Reads a <see cref="T:TagCollection" /> value.
    /// </summary>
    public abstract TagCollection ReadList();

    /// <summary>
    /// Reads a <see cref="T:TagDictionary" /> value.
    /// </summary>
    public abstract TagDictionary ReadCompound();

    /// <summary>
    /// Reads a <see cref="T:int[]" /> value.
    /// </summary>
    public abstract int[] ReadIntArray();

    /// <summary>
    /// Reads a <see cref="T:long[]" /> value.
    /// </summary>
    public abstract long[] ReadLongArray();


  }
}
